apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: elasticsearch
    role: master
  name: elasticsearch
  role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      initContainers:
        - name: init-myservice
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          volumeMounts:
            - name: elasticsearch-persistent-storage
              mountPath: "/usr/share/elasticsearch/data"
      containers:
        - name: elasticsearch
          imagePullPolicy: Never
          image: elasticsearch:8.3.3
          ports:
            - containerPort: 9200
              protocol: TCP
          env:
            - name: "TAKE_FILE_OWNERSHIP"
              value: "true"
          volumeMounts:
            - name: elasticsearch-persistent-storage
              mountPath: /usr/share/elasticsearch/data
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: jvm-config
              mountPath: "/usr/share/elasticsearch/config/jvm.options.d/jvm.options"
              subPath: jvm.options


      volumes:
        - name: config
          configMap:
            name: elasticsearch-config
        - name: jvm-config
          configMap:
            name: elasticsearch-jvm-config
        - name: elasticsearch-persistent-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pv-claim
