apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    xpack.security.enabled: false
    search.allow_expensive_queries: false
    cluster.routing.allocation.total_shards_per_node: 20
    node.roles: [master, data]
    node.name: data
    node.master: false
    node.data: true
    node.ingest: false
    discovery.seed_hosts: ["elasticsearch:9200"]
