apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-master-config
data:
  elasticsearch.yml: |
    logger.org.elasticsearch.discovery: TRACE
    network.host: 0.0.0.0
    cluster.name: es-cluster
    xpack.security.enabled: false
    search.allow_expensive_queries: false
    cluster.routing.allocation.total_shards_per_node: 20
    node.roles: [master]
    cluster.initial_master_nodes: ["elasticsearch-master-0"]
    discovery.seed_hosts: 
          - elasticsearch-master-0.elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
    - protocol: TCP
      port: 9300
      name: tcp
    - protocol: TCP
      port: 9200
      name: http

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: elasticsearch
    role: master
  name: elasticsearch-master
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - master
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-myservice
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
            - -c
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-master-data
              mountPath: "/usr/share/elasticsearch/data"
      containers:
        - name: elasticsearch-master
          imagePullPolicy: Never
          image: elasticsearch:8.3.3
          env:
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
          ports:
            - containerPort: 9300
              protocol: TCP
              name: tcp
            - containerPort: 9200
              protocol: TCP
              name: http
          volumeMounts:
            - name: elasticsearch-master-data
              mountPath: /usr/share/elasticsearch/data
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: config
          configMap:
            name: elasticsearch-master-config
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-volume-master
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/elasticsearch/master/data"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
            