apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    app: elasticsearch
    role: master
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
    