apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/C/Users/Okhanian/Desktop/logs"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete