apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      id: "logs"
      enabled: true
      paths:
       - '/usr/share/filebeat/logs/*/*.log'
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: elastic
      password: HIMS7BQzRqLM4Ly0HiXS
      ssl.verification_mode: none