apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        imagePullPolicy: Never
        image: kibana:8.3.3
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
          - containerPort: 5601
            protocol: TCP

